// Auto-generated by GenerateResources. Do not edit manually.
// Generated on: 2026-05-21

import Foundation

public struct Race: Sendable {
	public let id: Int
	public let name: String
	public let isFree: Bool

	public init(id: Int, name: String, isFree: Bool) {
		self.id = id
		self.name = name
		self.isFree = isFree
	}
}

public struct Terrain: Sendable {
	public let id: Int
	public let name: String
	public let isFree: Bool

	public init(id: Int, name: String, isFree: Bool) {
		self.id = id
		self.name = name
		self.isFree = isFree
	}
}

public let races: [Race] = [
	Race(id: 0, name: "Race 1", isFree: true),
	Race(id: 1, name: "Race 2", isFree: true),
	Race(id: 2, name: "Race 3", isFree: false),
]

public let terrains: [Terrain] = [
	Terrain(id: 0, name: "Terrain 1", isFree: true),
	Terrain(id: 1, name: "Terrain 2", isFree: true),
]
